version: "3.9"

services:
   redis:
      image: redis:alpine
      container_name: redis_fullstats
   db:
      image: postgres
      volumes:
         - postgres_data:/var/lib/postgresql/data
      environment:
         - POSTGRES_DB=${DB_NAME}
         - POSTGRES_USER=${DB_USER}
         - POSTGRES_PASSWORD=${DB_PASSWORD}
   web:
      build: .
      command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
      volumes:
         - .:/fullstats
      ports:
         - "8000:8000"
      depends_on:
         - db
      env_file:
         - .env
   celery_worker:
      restart: always
      build: .
      command: celery -A fullstats_test worker -l INFO
      volumes:
         - .:/fullstats_test
      container_name: celery_work_serv_chan
      depends_on:
         - db
         - redis
         - web
   celery_beat:
      restart: always
      build: .
      command: celery -A fullstats_test beat
      volumes:
         - .:/fullstats_test
      container_name: celery_beat_serv_chan
      depends_on:
         - db
         - redis
         - web
         - celery_worker

volumes:
   postgres_data: