version: "3.9"

services:
   redis:
      image: redis:alpine
      container_name: redis_fullstats
   db:
      image: postgres
      volumes:
         - postgres_data:/var/lib/postgresql/data
      environment:
         - POSTGRES_DB=fullstats
         - POSTGRES_USER=fullstats_admin
         - POSTGRES_PASSWORD=qwerty12345
   web:
      build: .
      entrypoint: ["/bin/sh","-c"]
      command:
         - | 
            python manage.py migrate
            python manage.py makemigrations
            python manage.py runserver 0.0.0.0:8000
      volumes:
         - .:/fullstats
      ports:
         - "8000:8000"
      environment:
         - POSTGRES_DB=fullstats
         - POSTGRES_USER=fullstats_admin
         - POSTGRES_PASSWORD=qwerty12345
      depends_on:
         - db
      env_file:
         - .env
   celery:
      restart: always
      build:
         context: .
      command: celery -A fullstats_test worker --loglevel=info -B
      volumes:
         - .:/django
      container_name: celery_beat_fullstats
      depends_on:
         - db
         - redis
         - web

volumes:
   postgres_data: