version: "3.9"

services:
   redis:
      image: redis:alpine
      container_name: redis
   db:
      image: postgres
      volumes:
         - postgres_data:/var/lib/postgresql/data
      environment:
         - POSTGRES_NAME=fullstats
         - POSTGRES_USER=fullstats_admin
         - POSTGRES_PASSWORD=qwerty12345
   web:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
         - .:/Blog
      ports:
         - "8000:8000"
      environment:
         - POSTGRES_NAME=fullstats
         - POSTGRES_USER=fullstats_admin
         - POSTGRES_PASSWORD=qwerty12345
      depends_on:
         - db
      env_file:
         - .env

volumes:
   postgres_data: